### ISSUE TITLE
[Syntax] /// Comment with 3 slashes not detected and breaks rest of file

### ISSUE THREAD

**Issue by tokyovigilante** [aerobounce/Swift-Next#2]
**Describe the syntax error**
`source.swift text.plain detected` rather than `source.swift comment.line.double-slash.swift punctuation.definition.comment.begin.swift`
Deleting third slash immediately restores correct behaviour.

**Expected behavior**
Correctly rendered function below comment.

**Minimum Reproducible Snippet of Swift code**
```swift
/// Compute the prefix sum of `seq`.
public func scan<S : Sequence, U>(_ seq: S, _ initial: U, _ combine: (U, S.Iterator.Element) -> U) -> [U] {
    var result: [U] = []
    return result
}
```
**Environment (please complete the following information):**
 - OS: Fedora rawhide
 - Sublime Text: 4148

**Comment by aerobounce** [comment]
Thanks for reporting, pushed some changes I had in local. Should be better now 👍

**Comment by tokyovigilante** [comment]
Thanks, fixed!
